version: '3.7'
services:
  utorrent:
    image: ekho/utorrent:latest
    volumes:
      - utorrent-settings:/utorrent/settings
      - /data/utorrent:/data
    environment:
      UID: 1000
      GID: 1000
      #webui: ng
      dir_autoload_delete: "true"
      dir_active: /data/active
      dir_completed: /data/completed
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  utorrent-settings:

# 1. $ sudo mkdir -p /data/utorrent/{active,download}
# 2. $ sudo chown -R kusumoto /data/utorrent
#       kusumoto uid = 1000 gid = 1000
# 3. $ sudo docker-compose up -d
# 4. access http://(server):8080/gui
#    --> admin / (no pass)
