version: '3.1'
services:
    owncloud:
        image: ak/owncloud:0.1
        restart: always
        ports:
            - 8081:80    
        volumes:
            - /data/owncloud/data:/data
            - storage:/data/kusumoto/files/storage
            - xtorage:/data/kusumoto/files/xtorage

    mysql:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: aktimecom
        volumes:
            - /data/owncloud/mysql:/var/lib/mysql

    proxy:
        image: ak/proxy:0.1
        restart: always
        ports:
            - 80:80    
            - 443:443  
        volumes:
            - letsencrypt:/etc/letsencrypt
            - /data/proxy/letsencrypt:/default/letsencrypt
volumes:
    letsencrypt:
    storage:
        driver_opts:
            type: nfs
            o: "addr=192.168.0.3,hard,rw,nolock"
            device: ":/s1/storage"
    xtorage:
        driver_opts:
            type: nfs
            o: "addr=192.168.0.5,hard,rw,nolock"
            device: ":/s2/xtorage"

## 1. # mkdir owncloud mysql
# 2. # docker-compose up -d
# 3. access http://localhost:8080
# 4. "Create an admin account"
#      Username = admin
#      Password = aktimecom
# 5. select "Storage & database" -> "MySQL/MariaDB"
#      Database use = root
#      Database password = aktimecom
#      Database name = owncloud
#      localhost = mysql
# 6. "Finish setup"
#
# You can log-in owncloud by "admin" / "aktimecom"
