version: '3.7'
services:
    owncloud:
        image: ak/owncloud:latest
        restart: always
        environment:
            TZ: Asia/Tokyo
        ports:
            - 8081:80    
        volumes:
            - /data/owncloud/data:/data
            - storage:/data/kusumoto/files/storage
            - xtorage:/data/kusumoto/files/xtorage

    mysql:
        image: mariadb
        restart: always
        environment:
            TZ: Asia/Tokyo
            MYSQL_ROOT_PASSWORD: aktimecom
        volumes:
            - /data/owncloud/mysql:/var/lib/mysql

    proxy:
        image: ak/proxy:latest
        restart: always
        environment:
            TZ: Asia/Tokyo
        ports:
            - 80:80    
            - 443:443  
        volumes:
            - letsencrypt:/etc/letsencrypt
            - /data/proxy/letsencrypt:/default/letsencrypt

    utorrent:
        image: ekho/utorrent:latest
        restart: always
        ports:
            - 8080:8080
            - 6881:6881
            - 6881:6881/udp
        volumes:
            - utorrent-settings:/utorrent/settings
            - /data/utorrent:/data
            - xtorage:/xtorage
        environment:
            TZ: Asia/Tokyo
            UID: 1000
            GID: 1000
            #webui: ng
            dir_autoload_delete: "true"
            dir_active: /data/active
            dir_completed: /xtorage/torrent

volumes:
    letsencrypt:
    storage:
        driver_opts:
            type: nfs
            o: "addr=192.168.0.3,hard,rw,nolock"
            device: ":/s1/storage"
    xtorage:
        driver_opts:
            type: nfs
            o: "addr=192.168.0.5,hard,rw,nolock"
            device: ":/s2/xtorage"
    utorrent-settings:

## 1. # mkdir owncloud mysql
# 2. # docker-compose up -d
# 3. access http://localhost:8080
# 4. "Create an admin account"
#      Username = admin
#      Password = aktimecom
# 5. select "Storage & database" -> "MySQL/MariaDB"
#      Database use = root
#      Database password = aktimecom
#      Database name = owncloud
#      localhost = mysql
# 6. "Finish setup"
#
# You can log-in owncloud by "admin" / "aktimecom"


## utorrent
# 1. $ sudo mkdir -p /data/utorrent/{active,download}
# 2. $ sudo chown -R kusumoto /data/utorrent
#       kusumoto uid = 1000 gid = 1000
# 3. $ sudo docker-compose up -d
# 4. access http://(server):8080/gui
#    --> admin / (no pass)
